name = "djc-r2-uploader"
main = "index.js"
compatibility_date = "2024-01-01"

# Binding R2 Bucket ke Worker
[[r2_buckets]]
binding = 'MY_R2_BUCKET'
bucket_name = 'web-kontraktor-djc'

# Environment variables (non-sensitive only)
[vars]
PUBLIC_R2_DOMAIN = "https://images.djckontraktor.com"
# UPLOAD_SECRET dipindah ke wrangler secret (terenkripsi)
